import datetime


photo_meta = [
    {
        "dt": datetime.datetime(2024, 3, 8, 9, 33, 46),
        "filename": "GOPR0098.JPG",
        "marker_type": "intermediate",
        "marker_number": "",
        "bottom_condition": "kelp",
    },
    {
        "dt": datetime.datetime(2024, 3, 8, 9, 33, 52),
        "filename": "GOPR0099.JPG",
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "unspecified",
    },
    {
        "dt": datetime.datetime(2024, 3, 8, 9, 34, 15),
        "filename": "GOPR0100.JPG",
        "marker_type": "intermediate",
        "marker_number": "",
        "bottom_condition": "unspecified",
    },
    {
        "dt": datetime.datetime(2024, 3, 8, 9, 34, 48),
        "filename": "GOPR0101.JPG",
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "unspecified",
    },
    {
        "dt": datetime.datetime(2024, 3, 8, 9, 34, 56),
        "filename": "GOPR0102.JPG",
        "marker_type": "numbered",
        "marker_number": 5,
        "bottom_condition": "rock",
    },
    {
        "dt": datetime.datetime(2024, 3, 8, 9, 35, 8),
        "filename": "GOPR0103.JPG",
        "marker_type": "numbered",
        "marker_number": 5,
        "bottom_condition": "unspecified",
    },
    {
        "dt": datetime.datetime(2024, 3, 8, 9, 35, 19),
        "filename": "GOPR0104.JPG",
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "unspecified",
    },
    {
        "dt": datetime.datetime(2024, 3, 8, 9, 35, 54),
        "filename": "GOPR0105.JPG",
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "unspecified",
    },
    {
        "dt": datetime.datetime(2024, 3, 8, 9, 36, 7),
        "filename": "GOPR0106.JPG",
        "marker_type": "intermediate",
        "marker_number": "",
        "bottom_condition": "unspecified",
    },
    {
        "dt": datetime.datetime(2024, 3, 8, 9, 36, 34),
        "filename": "GOPR0107.JPG",
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "unspecified",
    },
    {
        "dt": datetime.datetime(2024, 3, 8, 9, 37, 31),
        "filename": "GOPR0108.JPG",
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "unspecified",
    },
    {
        "dt": datetime.datetime(2024, 3, 8, 9, 37, 40),
        "filename": "GOPR0109.JPG",
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "unspecified",
    },
    {
        "dt": datetime.datetime(2024, 3, 8, 9, 37, 57),
        "filename": "GOPR0110.JPG",
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "unspecified",
    },
    {
        "dt": datetime.datetime(2024, 3, 8, 9, 38, 11),
        "filename": "GOPR0111.JPG",
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "unspecified",
    },
    {
        "dt": datetime.datetime(2024, 3, 8, 9, 39, 54),
        "filename": "GOPR0112.JPG",
        "marker_type": "numbered",
        "marker_number": 6,
        "bottom_condition": "unspecified",
    },
    {
        "dt": datetime.datetime(2024, 3, 8, 9, 40, 2),
        "filename": "GOPR0113.JPG",
        "marker_type": "numbered",
        "marker_number": 6,
        "bottom_condition": "unspecified",
    },
    {
        "dt": datetime.datetime(2024, 3, 8, 9, 40, 11),
        "filename": "GOPR0114.JPG",
        "marker_type": "numbered",
        "marker_number": 6,
        "bottom_condition": "unspecified",
    },
    {
        "dt": datetime.datetime(2024, 3, 8, 9, 40, 23),
        "filename": "GOPR0115.JPG",
        "marker_type": "numbered",
        "marker_number": 6,
        "bottom_condition": "unspecified",
    },
    {
        "dt": datetime.datetime(2024, 3, 8, 9, 43, 35),
        "filename": "GOPR0116.JPG",
        "marker_type": "intermediate",
        "marker_number": "",
        "bottom_condition": "unspecified",
    },
    {
        "dt": datetime.datetime(2024, 3, 8, 9, 43, 41),
        "filename": "GOPR0117.JPG",
        "marker_type": "intermediate",
        "marker_number": "",
        "bottom_condition": "unspecified",
    },
    {
        "dt": datetime.datetime(2024, 3, 8, 9, 43, 46),
        "filename": "GOPR0118.JPG",
        "marker_type": "intermediate",
        "marker_number": "",
        "bottom_condition": "unspecified",
    },
    {
        "dt": datetime.datetime(2024, 3, 8, 9, 44),
        "filename": "GOPR0119.JPG",
        "marker_type": "intermediate",
        "marker_number": "",
        "bottom_condition": "unspecified",
    },
    {
        "dt": datetime.datetime(2024, 3, 8, 9, 44, 10),
        "filename": "GOPR0120.JPG",
        "marker_type": "intermediate",
        "marker_number": "",
        "bottom_condition": "sandy",
    },
    {
        "dt": datetime.datetime(2024, 3, 8, 9, 44, 23),
        "filename": "GOPR0121.JPG",
        "marker_type": "intermediate",
        "marker_number": "",
        "bottom_condition": "sandy",
    },
    {
        "dt": datetime.datetime(2024, 3, 8, 9, 44, 28),
        "filename": "GOPR0122.JPG",
        "marker_type": "intermediate",
        "marker_number": "",
        "bottom_condition": "sandy",
    },
    {
        "dt": datetime.datetime(2024, 3, 8, 9, 44, 38),
        "filename": "GOPR0123.JPG",
        "marker_type": "intermediate",
        "marker_number": "",
        "bottom_condition": "sandy",
    },
    {
        "dt": datetime.datetime(2024, 3, 8, 9, 45, 2),
        "filename": "GOPR0124.JPG",
        "marker_type": "intermediate",
        "marker_number": "",
        "bottom_condition": "sandy",
    },
    {
        "dt": datetime.datetime(2024, 3, 8, 9, 45, 9),
        "filename": "GOPR0125.JPG",
        "marker_type": "intermediate",
        "marker_number": "",
        "bottom_condition": "sandy",
    },
    {
        "dt": datetime.datetime(2024, 3, 8, 9, 45, 31),
        "filename": "GOPR0126.JPG",
        "marker_type": "intermediate",
        "marker_number": "",
        "bottom_condition": "sandy",
    },
    {
        "dt": datetime.datetime(2024, 3, 8, 9, 45, 36),
        "filename": "GOPR0127.JPG",
        "marker_type": "intermediate",
        "marker_number": "",
        "bottom_condition": "sandy",
    },
    {
        "dt": datetime.datetime(2024, 3, 8, 9, 46, 6),
        "filename": "GOPR0128.JPG",
        "marker_type": "intermediate",
        "marker_number": "",
        "bottom_condition": "sandy",
    },
    {
        "dt": datetime.datetime(2024, 3, 8, 9, 46, 12),
        "filename": "GOPR0129.JPG",
        "marker_type": "intermediate",
        "marker_number": "",
        "bottom_condition": "sandy",
    },
    {
        "dt": datetime.datetime(2024, 3, 8, 9, 46, 22),
        "filename": "GOPR0130.JPG",
        "marker_type": "intermediate",
        "marker_number": "",
        "bottom_condition": "sandy",
    },
    {
        "dt": datetime.datetime(2024, 3, 8, 9, 46, 50),
        "filename": "GOPR0131.JPG",
        "marker_type": "intermediate",
        "marker_number": "",
        "bottom_condition": "sandy",
    },
    {
        "dt": datetime.datetime(2024, 3, 8, 9, 47, 1),
        "filename": "GOPR0132.JPG",
        "marker_type": "intermediate",
        "marker_number": "",
        "bottom_condition": "sandy",
    },
    {
        "dt": datetime.datetime(2024, 3, 8, 9, 47, 56),
        "filename": "GOPR0133.JPG",
        "marker_type": "intermediate",
        "marker_number": "",
        "bottom_condition": "sandy",
    },
    {
        "dt": datetime.datetime(2024, 3, 8, 9, 48, 12),
        "filename": "GOPR0134.JPG",
        "marker_type": "intermediate",
        "marker_number": "",
        "bottom_condition": "sandy",
    },
    {
        "dt": datetime.datetime(2024, 3, 8, 9, 48, 21),
        "filename": "GOPR0135.JPG",
        "marker_type": "intermediate",
        "marker_number": "",
        "bottom_condition": "sandy",
    },
    {
        "dt": datetime.datetime(2024, 3, 8, 9, 48, 52),
        "filename": "GOPR0136.JPG",
        "marker_type": "intermediate",
        "marker_number": "",
        "bottom_condition": "sandy",
    },
    {
        "dt": datetime.datetime(2024, 3, 8, 9, 48, 58),
        "filename": "GOPR0137.JPG",
        "marker_type": "intermediate",
        "marker_number": "",
        "bottom_condition": "sandy",
    },
    {
        "dt": datetime.datetime(2024, 3, 8, 9, 49, 10),
        "filename": "GOPR0138.JPG",
        "marker_type": "intermediate",
        "marker_number": "",
        "bottom_condition": "sandy",
    },
    {
        "dt": datetime.datetime(2024, 3, 8, 9, 49, 23),
        "filename": "GOPR0139.JPG",
        "marker_type": "intermediate",
        "marker_number": "",
        "bottom_condition": "sandy",
    },
    {
        "dt": datetime.datetime(2024, 3, 8, 9, 49, 29),
        "filename": "GOPR0140.JPG",
        "marker_type": "intermediate",
        "marker_number": "",
        "bottom_condition": "sandy",
    },
    {
        "dt": datetime.datetime(2024, 3, 8, 9, 49, 37),
        "filename": "GOPR0141.JPG",
        "marker_type": "intermediate",
        "marker_number": "",
        "bottom_condition": "sandy",
    },
    {
        "dt": datetime.datetime(2024, 3, 8, 9, 49, 45),
        "filename": "GOPR0142.JPG",
        "marker_type": "numbered",
        "marker_number": 8,
        "bottom_condition": "unspecified",
    },
    {
        "dt": datetime.datetime(2024, 3, 8, 9, 49, 52),
        "filename": "GOPR0143.JPG",
        "marker_type": "numbered",
        "marker_number": 8,
        "bottom_condition": "unspecified",
    },
    {
        "dt": datetime.datetime(2024, 3, 8, 9, 49, 59),
        "filename": "GOPR0144.JPG",
        "marker_type": "numbered",
        "marker_number": 8,
        "bottom_condition": "unspecified",
    },
    {
        "dt": datetime.datetime(2024, 3, 8, 9, 50, 40),
        "filename": "GOPR0145.JPG",
        "marker_type": "intermediate",
        "marker_number": "",
        "bottom_condition": "unspecified",
    },
    {
        "dt": datetime.datetime(2024, 3, 8, 9, 50, 59),
        "filename": "GOPR0146.JPG",
        "marker_type": "intermediate",
        "marker_number": "",
        "bottom_condition": "unspecified",
    },
    {
        "dt": datetime.datetime(2024, 3, 8, 9, 51, 15),
        "filename": "GOPR0147.JPG",
        "marker_type": "intermediate",
        "marker_number": "",
        "bottom_condition": "unspecified",
    },
    {
        "dt": datetime.datetime(2024, 3, 8, 9, 51, 38),
        "filename": "GOPR0148.JPG",
        "marker_type": "numbered",
        "marker_number": 9,
        "bottom_condition": "unspecified",
    },
    {
        "dt": datetime.datetime(2024, 3, 8, 9, 51, 49),
        "filename": "GOPR0149.JPG",
        "marker_type": "wildlife",
        "marker_number": "",
        "bottom_condition": "sandy",
    },
    {
        "dt": datetime.datetime(2024, 3, 8, 9, 52, 20),
        "filename": "GOPR0150.JPG",
        "marker_type": "intermediate",
        "marker_number": "",
        "bottom_condition": "sandy",
    },
    {
        "dt": datetime.datetime(2024, 3, 8, 9, 52, 57),
        "filename": "GOPR0151.JPG",
        "marker_type": "intermediate",
        "marker_number": "",
        "bottom_condition": "sandy",
    },
    {
        "dt": datetime.datetime(2024, 3, 8, 9, 53, 18),
        "filename": "GOPR0152.JPG",
        "marker_type": "intermediate",
        "marker_number": "",
        "bottom_condition": "sandy",
    },
    {
        "dt": datetime.datetime(2024, 3, 8, 9, 53, 49),
        "filename": "GOPR0153.JPG",
        "marker_type": "intermediate",
        "marker_number": "",
        "bottom_condition": "sandy",
    },
    {
        "dt": datetime.datetime(2024, 3, 8, 9, 54, 1),
        "filename": "GOPR0154.JPG",
        "marker_type": "intermediate",
        "marker_number": "",
        "bottom_condition": "unspecified",
    },
    {
        "dt": datetime.datetime(2024, 3, 8, 9, 54, 16),
        "filename": "GOPR0155.JPG",
        "marker_type": "numbered",
        "marker_number": 10,
        "bottom_condition": "unspecified",
    },
    {
        "dt": datetime.datetime(2024, 3, 8, 9, 54, 33),
        "filename": "GOPR0156.JPG",
        "marker_type": "numbered",
        "marker_number": 10,
        "bottom_condition": "unspecified",
    },
    {
        "dt": datetime.datetime(2024, 3, 8, 9, 54, 45),
        "filename": "GOPR0157.JPG",
        "marker_type": "intermediate",
        "marker_number": "",
        "bottom_condition": "unspecified",
    },
    {
        "dt": datetime.datetime(2024, 3, 8, 9, 55, 5),
        "filename": "GOPR0158.JPG",
        "marker_type": "intermediate",
        "marker_number": "",
        "bottom_condition": "unspecified",
    },
    {
        "dt": datetime.datetime(2024, 3, 8, 9, 55, 18),
        "filename": "GOPR0159.JPG",
        "marker_type": "intermediate",
        "marker_number": "",
        "bottom_condition": "unspecified",
    },
    {
        "dt": datetime.datetime(2024, 3, 8, 9, 56, 2),
        "filename": "GOPR0160.JPG",
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "unspecified",
    },
    {
        "dt": datetime.datetime(2024, 3, 8, 9, 56, 7),
        "filename": "GOPR0161.JPG",
        "marker_type": "numbered",
        "marker_number": 11,
        "bottom_condition": "unspecified",
    },
    {
        "dt": datetime.datetime(2024, 3, 8, 9, 56, 29),
        "filename": "GOPR0162.JPG",
        "marker_type": "intermediate",
        "marker_number": "",
        "bottom_condition": "kelp",
    },
    {
        "dt": datetime.datetime(2024, 3, 8, 9, 56, 36),
        "filename": "GOPR0163.JPG",
        "marker_type": "intermediate",
        "marker_number": "",
        "bottom_condition": "kelp",
    },
    {
        "dt": datetime.datetime(2024, 3, 8, 9, 57, 5),
        "filename": "GOPR0164.JPG",
        "marker_type": "numbered",
        "marker_number": 12,
        "bottom_condition": "unspecified",
    },
    {
        "dt": datetime.datetime(2024, 3, 8, 9, 57, 10),
        "filename": "GOPR0165.JPG",
        "marker_type": "numbered",
        "marker_number": 12,
        "bottom_condition": "unspecified",
    },
    {
        "dt": datetime.datetime(2024, 3, 8, 9, 57, 56),
        "filename": "GOPR0166.JPG",
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "unspecified",
    },
    {
        "dt": datetime.datetime(2024, 3, 8, 9, 58, 1),
        "filename": "GOPR0167.JPG",
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "unspecified",
    },
    {
        "dt": datetime.datetime(2024, 3, 8, 9, 58, 15),
        "filename": "GOPR0168.JPG",
        "marker_type": "intermediate",
        "marker_number": "",
        "bottom_condition": "unspecified",
    },
    {
        "dt": datetime.datetime(2024, 3, 8, 9, 58, 44),
        "filename": "GOPR0169.JPG",
        "marker_type": "intermediate",
        "marker_number": "",
        "bottom_condition": "unspecified",
    },
    {
        "dt": datetime.datetime(2024, 3, 8, 9, 58, 49),
        "filename": "GOPR0170.JPG",
        "marker_type": "intermediate",
        "marker_number": "",
        "bottom_condition": "unspecified",
    },
    {
        "dt": datetime.datetime(2024, 3, 8, 9, 59, 5),
        "filename": "GOPR0171.JPG",
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "unspecified",
    },
    {
        "dt": datetime.datetime(2024, 3, 8, 9, 59, 11),
        "filename": "GOPR0172.JPG",
        "marker_type": "numbered",
        "marker_number": 13,
        "bottom_condition": "unspecified",
    },
    {
        "dt": datetime.datetime(2024, 3, 8, 9, 59, 19),
        "filename": "GOPR0173.JPG",
        "marker_type": "numbered",
        "marker_number": 13,
        "bottom_condition": "unspecified",
    },
    {
        "dt": datetime.datetime(2024, 3, 8, 9, 59, 25),
        "filename": "GOPR0174.JPG",
        "marker_type": "numbered",
        "marker_number": 13,
        "bottom_condition": "unspecified",
    },
    {
        "dt": datetime.datetime(2024, 3, 8, 9, 59, 58),
        "filename": "GOPR0175.JPG",
        "marker_type": "intermediate",
        "marker_number": "",
        "bottom_condition": "unspecified",
    },
    {
        "dt": datetime.datetime(2024, 3, 8, 10, 0, 22),
        "filename": "GOPR0176.JPG",
        "marker_type": "intermediate",
        "marker_number": "",
        "bottom_condition": "unspecified",
    },
    {
        "dt": datetime.datetime(2024, 3, 8, 10, 1, 32),
        "filename": "GOPR0177.JPG",
        "marker_type": "numbered",
        "marker_number": 14,
        "bottom_condition": "unspecified",
    },
    {
        "dt": datetime.datetime(2024, 3, 8, 10, 1, 40),
        "filename": "GOPR0178.JPG",
        "marker_type": "numbered",
        "marker_number": 14,
        "bottom_condition": "unspecified",
    },
    {
        "dt": datetime.datetime(2024, 3, 8, 10, 1, 46),
        "filename": "GOPR0179.JPG",
        "marker_type": "numbered",
        "marker_number": 14,
        "bottom_condition": "unspecified",
    },
    {
        "dt": datetime.datetime(2024, 3, 8, 10, 2, 8),
        "filename": "GOPR0180.JPG",
        "marker_type": "intermediate",
        "marker_number": "",
        "bottom_condition": "unspecified",
    },
    {
        "dt": datetime.datetime(2024, 3, 8, 10, 2, 34),
        "filename": "GOPR0181.JPG",
        "marker_type": "intermediate",
        "marker_number": "",
        "bottom_condition": "unspecified",
    },
    {
        "dt": datetime.datetime(2024, 3, 8, 10, 2, 42),
        "filename": "GOPR0182.JPG",
        "marker_type": "intermediate",
        "marker_number": "",
        "bottom_condition": "unspecified",
    },
    {
        "dt": datetime.datetime(2024, 3, 8, 10, 3, 17),
        "filename": "GOPR0183.JPG",
        "marker_type": "intermediate",
        "marker_number": "",
        "bottom_condition": "unspecified",
    },
    {
        "dt": datetime.datetime(2024, 3, 8, 10, 3, 45),
        "filename": "GOPR0184.JPG",
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "unspecified",
    },
    {
        "dt": datetime.datetime(2024, 3, 8, 10, 3, 50),
        "filename": "GOPR0185.JPG",
        "marker_type": "numbered",
        "marker_number": 15,
        "bottom_condition": "kelp",
    },
    {
        "dt": datetime.datetime(2024, 3, 8, 10, 4, 36),
        "filename": "GOPR0186.JPG",
        "marker_type": "intermediate",
        "marker_number": "",
        "bottom_condition": "kelp",
    },
    {
        "dt": datetime.datetime(2024, 3, 8, 10, 5),
        "filename": "GOPR0187.JPG",
        "marker_type": "intermediate",
        "marker_number": "",
        "bottom_condition": "kelp",
    },
    {
        "dt": datetime.datetime(2024, 3, 8, 10, 5, 7),
        "filename": "GOPR0188.JPG",
        "marker_type": "intermediate",
        "marker_number": "",
        "bottom_condition": "kelp",
    },
    {
        "dt": datetime.datetime(2024, 3, 8, 10, 5, 26),
        "filename": "GOPR0189.JPG",
        "marker_type": "numbered",
        "marker_number": 16,
        "bottom_condition": "sandy",
    },
    {
        "dt": datetime.datetime(2024, 3, 8, 10, 5, 32),
        "filename": "GOPR0190.JPG",
        "marker_type": "numbered",
        "marker_number": 16,
        "bottom_condition": "sandy",
    },
    {
        "dt": datetime.datetime(2024, 3, 8, 10, 5, 55),
        "filename": "GOPR0191.JPG",
        "marker_type": "intermediate",
        "marker_number": "",
        "bottom_condition": "sandy",
    },
    {
        "dt": datetime.datetime(2024, 3, 8, 10, 6, 10),
        "filename": "GOPR0192.JPG",
        "marker_type": "intermediate",
        "marker_number": "",
        "bottom_condition": "unspecified",
    },
    {
        "dt": datetime.datetime(2024, 3, 8, 10, 6, 29),
        "filename": "GOPR0193.JPG",
        "marker_type": "intermediate",
        "marker_number": "",
        "bottom_condition": "kelp",
    },
    {
        "dt": datetime.datetime(2024, 3, 8, 10, 6, 47),
        "filename": "GOPR0194.JPG",
        "marker_type": "intermediate",
        "marker_number": "",
        "bottom_condition": "unspecified",
    },
    {
        "dt": datetime.datetime(2024, 3, 8, 10, 7),
        "filename": "GOPR0195.JPG",
        "marker_type": "intermediate",
        "marker_number": "",
        "bottom_condition": "unspecified",
    },
    {
        "dt": datetime.datetime(2024, 3, 8, 10, 7, 6),
        "filename": "GOPR0196.JPG",
        "marker_type": "intermediate",
        "marker_number": "",
        "bottom_condition": "unspecified",
    },
    {
        "dt": datetime.datetime(2024, 3, 8, 10, 7, 22),
        "filename": "GOPR0197.JPG",
        "marker_type": "intermediate",
        "marker_number": "",
        "bottom_condition": "kelp",
    },
    {
        "dt": datetime.datetime(2024, 3, 8, 10, 7, 36),
        "filename": "GOPR0198.JPG",
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "kelp",
    },
    {
        "dt": datetime.datetime(2024, 3, 8, 10, 7, 45),
        "filename": "GOPR0199.JPG",
        "marker_type": "numbered",
        "marker_number": 17,
        "bottom_condition": "unspecified",
    },
    {
        "dt": datetime.datetime(2024, 3, 8, 10, 8, 40),
        "filename": "GOPR0200.JPG",
        "marker_type": "numbered",
        "marker_number": 18,
        "bottom_condition": "unspecified",
    },
    {
        "dt": datetime.datetime(2024, 3, 8, 10, 8, 46),
        "filename": "GOPR0201.JPG",
        "marker_type": "numbered",
        "marker_number": 18,
        "bottom_condition": "unspecified",
    },
    {
        "dt": datetime.datetime(2024, 3, 8, 10, 9, 22),
        "filename": "GOPR0202.JPG",
        "marker_type": "numbered",
        "marker_number": 19,
        "bottom_condition": "unspecified",
    },
    {
        "dt": datetime.datetime(2024, 3, 8, 10, 9, 27),
        "filename": "GOPR0203.JPG",
        "marker_type": "numbered",
        "marker_number": 19,
        "bottom_condition": "unspecified",
    },
    {
        "dt": datetime.datetime(2024, 3, 8, 10, 9, 59),
        "filename": "GOPR0204.JPG",
        "marker_type": "intermediate",
        "marker_number": "",
        "bottom_condition": "unspecified",
    },
    {
        "dt": datetime.datetime(2024, 3, 8, 10, 10, 33),
        "filename": "GOPR0205.JPG",
        "marker_type": "numbered",
        "marker_number": 20,
        "bottom_condition": "unspecified",
    },
    {
        "dt": datetime.datetime(2024, 3, 8, 10, 10, 40),
        "filename": "GOPR0206.JPG",
        "marker_type": "numbered",
        "marker_number": 20,
        "bottom_condition": "unspecified",
    },
    {
        "dt": datetime.datetime(2024, 3, 8, 10, 11, 10),
        "filename": "GOPR0207.JPG",
        "marker_type": "intermediate",
        "marker_number": "",
        "bottom_condition": "unspecified",
    },
    {
        "dt": datetime.datetime(2024, 3, 8, 10, 12, 8),
        "filename": "GOPR0208.JPG",
        "marker_type": "numbered",
        "marker_number": 21,
        "bottom_condition": "unspecified",
    },
    {
        "dt": datetime.datetime(2024, 3, 8, 10, 12, 16),
        "filename": "GOPR0209.JPG",
        "marker_type": "numbered",
        "marker_number": 21,
        "bottom_condition": "unspecified",
    },
    {
        "dt": datetime.datetime(2024, 3, 8, 10, 12, 45),
        "filename": "GOPR0210.JPG",
        "marker_type": "intermediate",
        "marker_number": "",
        "bottom_condition": "unspecified",
    },
    {
        "dt": datetime.datetime(2024, 3, 8, 10, 13, 13),
        "filename": "GOPR0211.JPG",
        "marker_type": "numbered",
        "marker_number": 22,
        "bottom_condition": "unspecified",
    },
    {
        "dt": datetime.datetime(2024, 3, 8, 10, 13, 19),
        "filename": "GOPR0212.JPG",
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "unspecified",
    },
    {
        "dt": datetime.datetime(2024, 3, 8, 10, 14, 24),
        "filename": "GOPR0213.JPG",
        "marker_type": "numbered",
        "marker_number": 23,
        "bottom_condition": "kelp",
    },
    {
        "dt": datetime.datetime(2024, 3, 8, 10, 14, 30),
        "filename": "GOPR0214.JPG",
        "marker_type": "numbered",
        "marker_number": 23,
        "bottom_condition": "unspecified",
    },
    {
        "dt": datetime.datetime(2024, 3, 8, 10, 15, 46),
        "filename": "GOPR0215.JPG",
        "marker_type": "intermediate",
        "marker_number": "",
        "bottom_condition": "rocky",
    },
]
