import datetime

photo_meta = [
    {
        "filename": "GOPR0264.JPG",
        "datetime": datetime.datetime(2024, 3, 8, 12, 8, 19),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "low and rocky",
    },
    {
        "filename": "GOPR0274.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 8, 55, 3),
        "marker_type": "numbered",
        "chain_vertex": True,
        "marker_number": 3,
        "bottom_condition": "kelp",
    },
    {
        "filename": "GOPR0275.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 8, 55, 19),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "sandy",
    },
    {
        "filename": "GOPR0276.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 8, 55, 43),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "low and sandy",
    },
    {
        "filename": "GOPR0277.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 8, 56, 23),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "low and sandy",
    },
    {
        "filename": "GOPR0278.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 8, 58, 9),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "kelp",
    },
    {
        "filename": "GOPR0279.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 8, 58, 14),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "kelp",
    },
    {
        "filename": "GOPR0280.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 8, 59, 19),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "low and rocky",
    },
    {
        "filename": "GOPR0281.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 9, 0, 11),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "low and rocky",
    },
    {
        "filename": "GOPR0282.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 9, 1, 39),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "low and rocky",
    },
    {
        "filename": "GOPR0283.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 9, 1, 47),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "rocky",
    },
    {
        "filename": "GOPR0284.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 9, 1, 57),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "rocky",
    },
    {
        "filename": "GOPR0285.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 9, 2, 9),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "rocky",
    },
    {
        "filename": "GOPR0286.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 9, 2, 24),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "unspecified",
        "note": "Wobbegong Cave",
    },
    {
        "filename": "GOPR0287.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 9, 2, 48),
        "marker_type": "numbered",
        "chain_vertex": True,
        "marker_number": 6,
        "bottom_condition": "unspecified",
    },
    {
        "filename": "GOPR0288.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 9, 3, 16),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "low and rocky",
    },
    {
        "filename": "GOPR0289.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 9, 3, 24),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "low and rocky",
    },
    {
        "filename": "GOPR0290.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 9, 3, 33),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "sandy",
    },
    {
        "filename": "GOPR0291.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 9, 3, 43),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "sandy",
    },
    {
        "filename": "GOPR0292.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 9, 4, 10),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "sandy",
    },
    {
        "filename": "GOPR0293.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 9, 4, 15),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "sandy",
    },
    {
        "filename": "GOPR0294.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 9, 4, 30),
        "marker_type": "intermediate",
        "marker_number": "",
        "bottom_condition": "sandy",
    },
    {
        "filename": "GOPR0295.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 9, 4, 47),
        "marker_type": "intermediate",
        "marker_number": "",
        "bottom_condition": "sandy",
    },
    {
        "filename": "GOPR0296.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 9, 5, 6),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "sandy",
    },
    {
        "filename": "GOPR0297.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 9, 5, 48),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "sandy",
    },
    {
        "filename": "GOPR0298.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 9, 5, 57),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "sandy",
    },
    {
        "filename": "GOPR0299.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 9, 6, 10),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "sandy",
    },
    {
        "filename": "GOPR0300.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 9, 6, 53),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "sandy",
    },
    {
        "filename": "GOPR0301.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 9, 7, 36),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "sandy",
    },
    {
        "filename": "GOPR0302.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 9, 7, 50),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "sandy",
    },
    {
        "filename": "GOPR0303.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 9, 8, 6),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "sandy",
    },
    {
        "filename": "GOPR0304.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 9, 8, 42),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "sandy",
    },
    {
        "filename": "GOPR0305.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 9, 9, 5),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "sandy",
    },
    {
        "filename": "GOPR0306.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 9, 9, 45),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "sandy",
    },
    {
        "filename": "GOPR0307.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 9, 10, 4),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "low and sandy",
    },
    {
        "filename": "GOPR0308.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 9, 10, 29),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "sandy",
    },
    {
        "filename": "GOPR0309.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 9, 10, 52),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "sandy",
    },
    {
        "filename": "GOPR0310.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 9, 10, 59),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "sandy",
    },
    {
        "filename": "GOPR0311.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 9, 11, 10),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "sandy",
    },
    {
        "filename": "GOPR0312.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 9, 11, 24),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "sandy",
    },
    {
        "filename": "GOPR0313.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 9, 11, 52),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "sandy",
    },
    {
        "filename": "GOPR0314.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 9, 12, 3),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "sandy",
    },
    {
        "filename": "GOPR0315.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 9, 12, 17),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "rocky",
        "note": "Tire",
    },
    {
        "filename": "GOPR0316.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 9, 12, 38),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "sandy",
    },
    {
        "filename": "GOPR0317.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 9, 13, 27),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "rocky",
    },
    {
        "filename": "GOPR0318.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 9, 14, 49),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "rocky",
    },
    {
        "filename": "GOPR0319.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 9, 15, 43),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "sandy",
    },
    {
        "filename": "GOPR0320.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 9, 16, 44),
        "marker_type": "unnumbered",
        "marker_number": "",
        "bottom_condition": "kelp",
    },
    {
        "filename": "GOPR0321.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 9, 16, 53),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "kelp",
    },
    {
        "filename": "GOPR0322.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 9, 17, 29),
        "marker_type": "numbered",
        "chain_vertex": True,
        "marker_number": 20,
        "bottom_condition": "kelp",
    },
    {
        "filename": "GOPR0323.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 9, 18, 25),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "kelp",
    },
    {
        "filename": "GOPR0324.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 9, 18, 59),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "sandy and kelp",
    },
    {
        "filename": "GOPR0325.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 9, 19, 21),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "sandy and kelp",
    },
    {
        "filename": "GOPR0326.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 9, 19, 41),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "low and sandy",
    },
    {
        "filename": "GOPR0327.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 9, 20, 9),
        "marker_type": "unnumbered",
        "marker_number": "",
        "bottom_condition": "low and sandy",
    },
    {
        "filename": "GOPR0328.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 9, 20, 21),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "sandy and rocky",
    },
    {
        "filename": "GOPR0329.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 9, 20, 26),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "low and sandy",
    },
    {
        "filename": "GOPR0330.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 9, 20, 36),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "rocky",
    },
    {
        "filename": "GOPR0331.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 9, 20, 50),
        "marker_type": "numbered",
        "chain_vertex": True,
        "marker_number": 22,
        "bottom_condition": "unspecified",
    },
    {
        "filename": "GOPR0332.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 9, 21, 7),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "low and sandy",
    },
    {
        "filename": "GOPR0333.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 9, 21, 24),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "low and sandy",
    },
    {
        "filename": "GOPR0334.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 9, 22, 3),
        "marker_type": "numbered",
        "chain_vertex": True,
        "marker_number": 23,
        "bottom_condition": "unspecified",
    },
    {
        "filename": "GOPR0335.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 9, 22, 10),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "low and rocky",
    },
    {
        "filename": "GOPR0336.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 9, 23, 41),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "sandy",
    },
    {
        "filename": "GOPR0337.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 9, 23, 53),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "rocky",
    },
    {
        "filename": "GOPR0338.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 9, 24, 35),
        "marker_type": "intermediate",
        "marker_number": 23.2,
        "bottom_condition": "unspecified",
    },
    {
        "filename": "GOPR0339.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 9, 24, 42),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "low and rocky",
    },
    {
        "filename": "GOPR0340.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 9, 24, 58),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "rocky",
    },
    {
        "filename": "GOPR0341.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 9, 25, 25),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "low",
    },
    {
        "filename": "GOPR0342.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 9, 25, 31),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "low",
    },
    {
        "filename": "GOPR0343.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 9, 25, 41),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "low and sandy",
    },
    {
        "filename": "GOPR0344.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 9, 26, 39),
        "marker_type": "numbered",
        "chain_vertex": True,
        "marker_number": 24,
        "bottom_condition": "unspecified",
    },
    {
        "filename": "GOPR0345.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 9, 27, 35),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "rocky",
    },
    {
        "filename": "GOPR0346.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 9, 27, 50),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "rocky",
    },
    {
        "filename": "GOPR0347.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 9, 30, 5),
        "marker_type": "numbered",
        "chain_vertex": True,
        "marker_number": 25,
        "bottom_condition": "unspecified",
    },
    {
        "filename": "GOPR0348.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 9, 30, 15),
        "marker_type": "numbered",
        "chain_vertex": True,
        "marker_number": 25,
        "bottom_condition": "unspecified",
    },
    {
        "filename": "GOPR0349.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 9, 31, 25),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "sandy",
    },
    {
        "filename": "GOPR0350.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 9, 33, 55),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "sandy",
    },
    {
        "filename": "GOPR0351.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 9, 34, 29),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "sandy",
    },
    {
        "filename": "GOPR0352.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 9, 35, 4),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "sandy",
    },
    {
        "filename": "GOPR0353.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 9, 35, 24),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "rocky",
    },
    {
        "filename": "GOPR0354.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 9, 35, 28),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "low and rocky",
    },
    {
        "filename": "GOPR0355.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 9, 36, 28),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "rocky",
    },
    {
        "filename": "GOPR0356.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 9, 36, 32),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "rocky",
    },
    {
        "filename": "GOPR0357.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 9, 36, 38),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "rocky",
    },
    {
        "filename": "GOPR0358.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 9, 37, 18),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "rocky",
    },
    {
        "filename": "GOPR0359.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 9, 37, 37),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "rocky",
    },
    {
        "filename": "GOPR0360.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 9, 37, 51),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "rocky",
    },
    {
        "filename": "GOPR0361.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 9, 40, 4),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "rocky",
    },
    {
        "filename": "GOPR0362.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 9, 40, 24),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "rocky",
    },
    {
        "filename": "GOPR0363.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 9, 42, 17),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "rocky",
    },
    {
        "filename": "GOPR0364.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 9, 43, 49),
        "marker_type": "numbered",
        "chain_vertex": True,
        "marker_number": 1,
        "bottom_condition": "unspecified",
    },
    {
        "filename": "GOPR0366.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 11, 12, 55),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "low and rocky",
    },
    {
        "filename": "GOPR0367.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 11, 13, 14),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "rocky",
    },
    {
        "filename": "GOPR0368.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 11, 15, 3),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "rocky",
    },
    {
        "filename": "GOPR0369.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 11, 15, 13),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "rocky",
    },
    {
        "filename": "GOPR0370.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 11, 15, 18),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "rocky",
    },
    {
        "filename": "GOPR0371.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 11, 17, 21),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "sandy",
    },
    {
        "filename": "GOPR0372.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 11, 17, 37),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "sandy",
    },
    {
        "filename": "GOPR0373.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 11, 17, 47),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "sandy",
    },
    {
        "filename": "GOPR0374.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 11, 17, 57),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "kelp",
    },
    {
        "filename": "GOPR0375.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 11, 18, 3),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "kelp",
    },
    {
        "filename": "GOPR0376.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 11, 18, 16),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "kelp",
    },
    {
        "filename": "GOPR0377.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 11, 18, 23),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "sandy",
    },
    {
        "filename": "GOPR0378.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 11, 18, 34),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "sandy",
    },
    {
        "filename": "GOPR0379.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 11, 19, 18),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "sandy",
    },
    {
        "filename": "GOPR0380.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 11, 19, 30),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "sandy",
    },
    {
        "filename": "GOPR0381.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 11, 20, 22),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "low and sandy",
    },
    {
        "filename": "GOPR0382.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 11, 20, 32),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "sandy",
    },
    {
        "filename": "GOPR0383.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 11, 20, 53),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "kelp",
    },
    {
        "filename": "GOPR0384.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 11, 21, 14),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "kelp",
    },
    {
        "filename": "GOPR0385.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 11, 21, 20),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "kelp",
    },
    {
        "filename": "GOPR0386.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 11, 21, 28),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "kelp",
    },
    {
        "filename": "GOPR0387.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 11, 22, 35),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "rocky",
    },
    {
        "filename": "GOPR0388.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 11, 22, 55),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "sandy",
    },
    {
        "filename": "GOPR0389.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 11, 23),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "sandy",
        "note": "Wobbegong cave",
    },
    {
        "filename": "GOPR0390.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 11, 23, 14),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "sandy",
    },
    {
        "filename": "GOPR0391.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 11, 25, 33),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "sandy",
    },
    {
        "filename": "GOPR0392.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 11, 25, 43),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "sandy",
    },
    {
        "filename": "GOPR0393.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 11, 25, 47),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "sandy",
    },
    {
        "filename": "GOPR0394.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 11, 26, 14),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "kelp",
    },
    {
        "filename": "GOPR0395.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 11, 26, 33),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "sandy",
    },
    {
        "filename": "GOPR0396.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 11, 26, 39),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "sandy",
    },
    {
        "filename": "GOPR0397.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 11, 26, 51),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "sandy",
    },
    {
        "filename": "GOPR0398.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 11, 27, 28),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "sandy",
    },
    {
        "filename": "GOPR0399.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 11, 28, 27),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "sandy",
    },
    {
        "filename": "GOPR0400.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 11, 28, 44),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "kelp",
    },
    {
        "filename": "GOPR0401.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 11, 28, 54),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "kelp",
    },
    {
        "filename": "GOPR0402.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 11, 29, 8),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "kelp",
    },
    {
        "filename": "GOPR0403.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 11, 29, 53),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "rocky",
    },
    {
        "filename": "GOPR0404.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 11, 29, 57),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "rocky",
    },
    {
        "filename": "GOPR0405.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 11, 30, 31),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "kelp",
    },
    {
        "filename": "GOPR0406.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 11, 31, 26),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "low and sandy",
    },
    {
        "filename": "GOPR0407.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 11, 31, 36),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "rocky",
    },
    {
        "filename": "GOPR0408.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 11, 34, 21),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "low and rocky",
    },
    {
        "filename": "GOPR0409.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 11, 34, 56),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "rocky",
    },
    {
        "filename": "GOPR0410.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 11, 35, 2),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "rocky",
        "note": "wobbegong cave",
    },
    {
        "filename": "GOPR0411.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 11, 35, 10),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "rocky",
    },
    {
        "filename": "GOPR0412.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 11, 35, 16),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "rocky",
    },
    {
        "filename": "GOPR0413.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 11, 35, 56),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "rocky",
    },
    {
        "filename": "GOPR0414.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 11, 36, 2),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "sandy",
    },
    {
        "filename": "GOPR0415.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 11, 36, 29),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "sandy",
        "note": "Zoanthus Robustus",
    },
    {
        "filename": "GOPR0416.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 11, 37, 12),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "sandy",
    },
    {
        "filename": "GOPR0418.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 11, 39, 6),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "sandy",
    },
    {
        "filename": "GOPR0419.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 11, 39, 8),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "sandy",
    },
    {
        "filename": "GOPR0420.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 11, 39, 14),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "sandy",
    },
    {
        "filename": "GOPR0421.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 11, 40, 3),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "sandy",
    },
    {
        "filename": "GOPR0422.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 11, 40, 10),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "kelp",
    },
    {
        "filename": "GOPR0423.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 11, 40, 18),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "kelp",
    },
    {
        "filename": "GOPR0424.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 11, 40, 26),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "low",
    },
    {
        "filename": "GOPR0425.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 11, 40, 42),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "sandy",
    },
    {
        "filename": "GOPR0426.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 11, 41, 19),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "sandy",
    },
    {
        "filename": "GOPR0427.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 11, 41, 24),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "kelp",
    },
    {
        "filename": "GOPR0428.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 11, 41, 46),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "sandy",
    },
    {
        "filename": "GOPR0429.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 11, 41, 51),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "kelp",
    },
    {
        "filename": "GOPR0430.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 11, 44, 26),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "unspecified",
    },
    {
        "filename": "GOPR0431.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 11, 44, 32),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "unspecified",
    },
    {
        "filename": "GOPR0432.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 11, 44, 38),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "unspecified",
    },
    {
        "filename": "GOPR0433.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 11, 44, 57),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "unspecified",
    },
    {
        "filename": "GOPR0434.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 11, 45, 17),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "sandy",
    },
    {
        "filename": "GOPR0435.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 11, 45, 22),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "sandy",
    },
    {
        "filename": "GOPR0436.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 11, 48, 20),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "sandy",
    },
    {
        "filename": "GOPR0437.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 11, 48, 35),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "kelp",
    },
    {
        "filename": "GOPR0438.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 11, 53, 11),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "sandy",
    },
    {
        "filename": "GOPR0439.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 11, 53, 14),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "sandy",
    },
    {
        "filename": "GOPR0440.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 11, 53, 25),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "kelp",
    },
    {
        "filename": "GOPR0441.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 11, 53, 35),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "kelp",
    },
    {
        "filename": "GOPR0442.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 11, 53, 38),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "kelp",
    },
    {
        "filename": "GOPR0443.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 11, 56, 35),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "unspecified",
    },
    {
        "filename": "GOPR0444.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 11, 56, 40),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "low and sandy",
    },
    {
        "filename": "GOPR0445.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 11, 56, 43),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "low and sandy",
    },
    {
        "filename": "GOPR0446.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 11, 57, 3),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "low and sandy",
    },
    {
        "filename": "GOPR0447.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 11, 57, 57),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "sandy",
    },
    {
        "filename": "GOPR0448.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 11, 58, 27),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "sandy",
    },
    {
        "filename": "GOPR0449.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 11, 58, 31),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "sandy",
    },
    {
        "filename": "GOPR0450.JPG",
        "datetime": datetime.datetime(2024, 3, 23, 11, 58, 37),
        "marker_type": "",
        "marker_number": "",
        "bottom_condition": "sandy",
    },
]
